-dontwarn java.lang.reflect.AnnotatedType
-keep class io.github.andrealtb.coloroslyrics.provider.salt.HookEntry { *; }
-keep class io.github.andrealtb.coloroslyrics.provider.salt.** { *; }
-repackageclasses ''
